export const IO = {
  START_CHANNEL: 'IO.START_CHANNEL',
  STOP_CHANNEL: 'IO.STOP_CHANNEL',
  CHANNEL_ON: 'IO.CHANNEL_ON',
  CHANNEL_OFF: 'IO.CHANNEL_OFF',
  SERVER_ON: 'IO.SERVER_ON',
  SERVER_OFF: 'IO.SERVER_OFF'
};
